### ISSUE TITLE
Featurerequest - Possibility to suppress color in the Event List Widget

### ISSUE THREAD

**Issue by mabstrei** [the-events-calendar/the-events-calendar-category-colors#154]
Is it possible to ad the Possibility to suppress colors for the Event List Widget?

e.g. We have the Event List Widget on our startpage and would like to have this widget without any colors.

A suppression for specific sites would also be possible.

**Comment by afragen** [comment]
At this time removing the colors from the widgets is not possible.

**Comment by afragen** [comment]
Not certain but it might be possible using CSS.
