### ISSUE TITLE
Issue with update Wordpress 6.5.5

### ISSUE THREAD

**Issue by odincreation** [the-events-calendar/the-events-calendar-category-colors#157]
Hi, the plugin doesn´t show colors since the last update of Wordpress... Could you solve it and fix it? It was ok before the update.  Thanks a lot,
I have this message too: Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in .../public_html/wp-content/plugins/the-events-calendar-category-colors/src/Category_Colors/Main.php on line 260

**Comment by afragen** [comment]
FWIW my test site at https://tribe.thefragens.net is running the latest versions of the relevant plugins and WP 6.6-RC2, PHP 8.3.3. 

Everything seems to work for me with no errors. Have you tried saving the settings again?

**Comment by odincreation** [comment]
Yes, but it doesn´t run... If it´s not a WP update problem, it may be due to the fact that events have 2 categories? Some of the colors appeared yesterday, not all, then I did some changes on the color of one button, and they all have disappeared once again after saving. I am lost...

**Comment by afragen** [comment]
What do you mean, "it doesn't run"?

Can screenshot your settings and describe what you think it should look like?

**Comment by odincreation** [comment]
I mean, the categories don't seem to be what they should be.
![Ajustes-—-WordPress](https://github.com/the-events-calendar/the-events-calendar-category-colors/assets/174655083/6d58958d-4cb1-4b39-b54a-d6d466ef6aef)
![Eventos-en-mayo-2024](https://github.com/the-events-calendar/the-events-calendar-category-colors/assets/174655083/b7e5f1f9-4e4e-4d90-aa11-ce1c39c93bd3)

**Comment by odincreation** [comment]
Front end, there is only one color, the current categories have no transparency, the others have transparency.

**Comment by afragen** [comment]
Can you provide the URL of your calendar?

Have you tried to see if you have a plugin conflict? Deactivate all plugins except those from The Events Calendar, does the issue persist?

If it does can you temporarily activate a default theme and see if it persists?

**Comment by afragen** [comment]
Can you uncheck the featured event color and save settings?

Also, if you want a solid background only you don't need to set the border color.

**Comment by odincreation** [comment]
I have deactivated all plugins and activated a default theme, but the issue persists... Here is the url of the calendar: https://solsticio.com.bo/eventos/mes/2024-06/ I will let it on line for a few hours. Thanks a lot for your help

**Comment by afragen** [comment]
I don't see anything on that page but an header and and image. No menus, no calendar.

**Comment by odincreation** [comment]
And now?

**Comment by afragen** [comment]
Much better. I see the following error inside the generated CSS for the plugin. 

```
<br /> <b>Deprecated</b>: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in <b>/home/heddjhik/public_html/wp-includes/kses.php</b> on line <b>1745</b><br /> 
```

I'll try to look closer as soon as I have some time. I'll let you know when I have something else to test with. 

What PHP version are you using?

**Comment by afragen** [comment]
I think I might see an issue. Still need to further test.

**Comment by afragen** [comment]
Can you try this branch and see if it works?

https://github.com/afragen/the-events-calendar-category-colors/archive/refs/heads/develop.zip

**Comment by odincreation** [comment]
Yes,  I had mentioned this error in my first message. Thank you very much for your time!
I use PHP 8.1

**Comment by odincreation** [comment]
Thank you, I had install and replace the plugin but the result is the same...

**Comment by afragen** [comment]
Seems like the plugin from the develop branch is not installed as the version is 7.3.0.1 and the CSS still shows version 7.3.0.

Also you can add the `refresh_css` query arg to the calendar URL to refresh the CSS.

**Comment by odincreation** [comment]
Super! It works perfectly, thank you very much for your disponibility and your great work! :)

**Comment by afragen** [comment]
It looks like you have two categories with the same coloring. You might need to set it and save again. 

Thanks for testing and glad it works. Make sure the plugin is in the `wp-content/plugins/the-events-calendar-category-colors` folder so the plugin will update correctly.

**Comment by odincreation** [comment]
If you look at the picture the category Enersol´s background should be grey, it takes the colour yellow of the Mantenimiento´s background. If I change the color of this one, the bg colour of Enersol change too. This issue concerns the calendar elements, not the buttons who have the good appearance

**Comment by afragen** [comment]
Now I see what you're referring to, though it looks like the backgrounds for all the categories that have borders is white and it might be better to set those to transparent. The picture doesn't show the background as gray.
