### ISSUE TITLE
background colour of the event doesn´t match with his button

### ISSUE THREAD

**Issue by odincreation** [the-events-calendar/the-events-calendar-category-colors#160]
Hi, I post a new issue because the #157 were closed.
As I show on the picture, the button/category "Enersol" has a pale grey background, and the events corresponding to this category in the calendar appear with a yellow background, which correspond to the category "Mantenimiento" (and "Limpieza" too, but after testing changing colours, it appears that Enersol take the Mantemiento´s background.
If I quit the background of Enersol, it occurs the same.
Could you help me to fix this please? Thanks a lot!

![Eventos-en-septiembre-2024](https://github.com/the-events-calendar/the-events-calendar-category-colors/assets/174655083/ec970c4e-066f-4ff7-bb76-97b275ccf74c)
![Ajustes-—-WordPress (1)](https://github.com/the-events-calendar/the-events-calendar-category-colors/assets/174655083/ae491f48-70a9-40f7-b035-67486b8e3c68)

**Comment by afragen** [comment]
Can you again share the calendar URL?

**Comment by odincreation** [comment]
https://solsticio.com.bo/eventos/mes/2024-09/

**Comment by afragen** [comment]
So here's what's happening. You have 2 categories selected for those events. 

```
Categorías del Evento:
Enersol, Mantenimiento
```

Since one category has both border and background and the other has background the order of precedence in CSS takes over. The CSS is written out alphabetically. 

This means the event has a border of one category and a background of another. This is an issue when assigning more than one category to an event.

**Comment by odincreation** [comment]
I understand... And there's nothing to do? How could I resolve it? I really need to have both categories, and visually to distinguish tasks and providers...

**Comment by afragen** [comment]
You could have one category with just a border and one with just the background. Use transparent for the non-colored border/background. The combination will display.

**Comment by odincreation** [comment]
I´ve tried it but it doesn´t work. I found a solution renaming the tasks as "1-mantenimiento" and "2-limpieza" to appear before suppliers, and it's working. Not ideal, but a solution!
