### ISSUE TITLE
categories colors don´t display on phone view

### ISSUE THREAD

**Issue by odincreation** [the-events-calendar/the-events-calendar-category-colors#162]
Hi Andy, and thanks for your great work! 
I would like to have the same effect with phone view than with desktop view: As you can see in the screenshot, the points in day events appears as grey points, with 100% opacity and don´t show the colors of the categories. Would it be possible to have the points with colors and opacity as in desktop view? I would like to be able to see the categories without having to click. Thanks for your help
![Eventos-en-junio-2024](https://github.com/user-attachments/assets/cf356f3f-42a3-4b85-aee1-28fd5f6e797a)
![Eventos-en-junio-2024 (1)](https://github.com/user-attachments/assets/ddedc8fa-da42-4618-a124-ee2d61f0c538)

**Comment by afragen** [comment]
Past events have a built in opacity that is part of TEC. Nothing to change in the Category Colors plugin.
