### ISSUE TITLE
Can't Unhide or Color New Categories

### ISSUE THREAD

**Issue by Pinakothek** [the-events-calendar/the-events-calendar-category-colors#167]
An Events Calendar update has broken some Category Color functions. 

I cannot "Unhide" or "Style" a new category. I can make the changes but they revert when I click "SAVE".

The Events Calendar v6.7.0
The Events Calendar Pro v7.2.0
WordPress v6.6.2
PHP v8.2.24

<img width="773" alt="Calendar Colors - Screenshot" src="https://github.com/user-attachments/assets/d4702704-194a-48fe-b907-69efe15ba7d1">

**Comment by philipverner** [comment]
yes i seem to be having the same problem

**Comment by philipverner** [comment]
i was able to resolve my issue by uploading to the development code

**Comment by Pinakothek** [comment]
Thanks for your reply to my post. I don't understand what you mean by "uploading to the development code".

**Comment by afragen** [comment]
I'm pretty sure @philipverner Mena's using the `develop` branch.

**Comment by afragen** [comment]
This should be fixed in 7.4.0 release.
